# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'live-supplier' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for live-supplier

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  
  # For FB
  
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'

end
